Event mails only to selected year students
CommunityOfCoders/COCWebsite pull request #167
Opened 2021-12-06 13:13 UTC by RaviMauryaHootowl

Solves #166 

When adding a new event, the admin gets the option to select a range of Graduation Years. Initial Event mails are sent only to those students. 
Later, any student irrespective of their Grad Year can register and receive notification for that before the event starts.

(also, if we don't want to send mails to anyone, just put any bigger year like 2030, 2030 😂)

![image](https://user-images.githubusercontent.com/59064326/144850173-6a05ae89-a5c4-487c-9418-4685544d3daf.png)

Auto Refresh Token is also implemented for Events(Create, Update, Delete) using the `useAuthenticatedAxios` Hook made in the last PR.

There are also slight schema changes for the database, graduationYear is replaced by graduationYearFrom and graduationYearTo in Events.
There doesn't seem any conflicts with previous data with the old schema as this graduationYearFrom and graduationYearTo fields are only used for sending emails initially.

If there are any changes, do let me know. Thanks!

2021-12-06 13:25 UTC, Saif807380 commented on new_client/src/components/events/AddEvent.jsx
> +                <Grid item xs={30}>
I think 12 is the maximum value

2021-12-06 13:27 UTC, Saif807380 commented on new_client/src/components/events/AddEvent.jsx
> +                    label="From Graduation year"
g should be lowercase

2021-12-06 13:27 UTC, Saif807380 commented on new_client/src/components/events/AddEvent.jsx
>                    <TextField
Can we add a little spacing between the two textfields?

2021-12-06 13:39 UTC, Saif807380 requested changes

2021-12-06 13:39 UTC, Saif807380 commented on new_client/src/components/events/AddEvent.jsx
> +                <Grid item xs={30}>
I think 12 is the maximum value

2021-12-06 13:39 UTC, Saif807380 commented on new_client/src/components/events/AddEvent.jsx
> +                    label="From Graduation year"
g should be lowercase

2021-12-06 13:39 UTC, Saif807380 commented on new_client/src/components/events/AddEvent.jsx
>                    <TextField
Can we add a little spacing between the two textfields?

2021-12-07 06:43 UTC, RaviMauryaHootowl commented
Made the above changes and also shifted verifyToken from AuthController to auth middleware.

2021-12-07 06:54 UTC, Saif807380 approved these changes

2021-12-07 10:37 UTC, ShubhankarKG approved these changes

2021-12-07 10:38 UTC, merged