Modified Interview and Company APIs
CommunityOfCoders/COCWebsite pull request #201
Opened 2022-03-24 07:08 UTC by shahparth36

Added cache and login middleware to interview and company apis.

2022-03-24 09:42 UTC, ShubhankarKG requested changes

2022-03-24 09:42 UTC, ShubhankarKG commented on server/src/controllers/CompanyController.js
> +        // next();
Please remove comments if not needed. Also, if next is not needed we can remove it.

2022-03-24 09:42 UTC, ShubhankarKG commented on server/src/controllers/InterviewController.js
> +        // next();
Please remove the comments and the next parameter if not needed.

2022-03-26 08:17 UTC, shahparth36 commented
Have removed comments from controller as requested

2022-03-26 09:10 UTC, ShubhankarKG approved these changes

2022-03-27 12:52 UTC, merged

2022-03-27 12:53 UTC, RaviMauryaHootowl commented
Thanks!