#30 Added a basic navbar for the desktop version and added code to switch classes on window resize.
CommunityOfCoders/COCWebsite pull request #47
Opened 2020-12-20 08:03 UTC by kkothari2001

Pls feel free to suggest any changes in UI that might be required! I'm currently working on the mobile navigation

2020-12-22 11:07 UTC, kkothari2001 commented
Am commiting the responsive navbar

2020-12-23 04:15 UTC, ShubhankarKG requested changes
Hi, thanks for the pull request! Just a couple more changes needed :pray: 

1. Please use the routes created in `App.js` and apply them to the `Link` tags.
2. I personally feel that the menubar in mobile should be on the left hand side.
3. Some icons were used in the earlier version of the `Header`. We would like that to be used as well, atleast in the hamburger menu if possible.

Let's wait for 2 and 3 first until @Saif807380 has a look at it. We would definitely want 1 to be started with.

Thanks!

2020-12-23 05:11 UTC, Saif807380 commented
The navbar looks great! Just a few changes - 

- Can we add a separator between each of the items? Something like this 
<img width="717" alt="Screenshot 2020-12-23 at 10 35 16" src="https://user-images.githubusercontent.com/50794619/102961649-d9bd8d80-450a-11eb-95b2-34e03af63096.png">

- Even I think that the mobile menubar and hamburger should be on the left
- Icons in the mobile menubar would look great
- We can highlight the current tab corresponding to the current page

Thanks!

2020-12-23 06:48 UTC, kkothari2001 commented
> Hi, thanks for the pull request! Just a couple more changes needed 🙏
> 
> 1. Please use the routes created in `App.js` and apply them to the `Link` tags.
> 2. I personally feel that the menubar in mobile should be on the left hand side.
> 3. Some icons were used in the earlier version of the `Header`. We would like that to be used as well, atleast in the hamburger menu if possible.
> 
> Let's wait for 2 and 3 first until @Saif807380 has a look at it. We would definitely want 1 to be started with.
> 
> Thanks!

@ShubhankarKG  What do I link the "Resources" and "Projects" <Link> to?

I'm working on the other changes suggested by you and @Saif807380

2020-12-24 12:20 UTC, ShubhankarKG requested changes
Thanks for the updates! :pray: 

Can you create a function that can do the string generation part? 

I'll try to give you a heads up:

```jsx
const [currentRoute, setCurrentRoute] = useState("Home");

const classNames = (routeToGo) => {
    // Add logic for isDesktop / isMobile
    if (routeToGo === currentRoute) {
       // Add required classnanes.
    }
}

```

Maybe you can work out the state logic from here on.

2020-12-24 12:20 UTC, ShubhankarKG commented on new_client/src/components/Header.js
> +		document.getElementById("nav-toggler").addEventListener("click", navToggle);
if we are adding an eventListener, we should ensure that we remove the eventListener when the component unmounts, in other words, return from useEffect `removeEventListener`.

2020-12-24 12:20 UTC, ShubhankarKG commented on new_client/src/components/Header.js
> +					className={isDesktop ? "nav-item-desk" : "nav-item-mob"}
Since we are duplicating the same code logic for className, it makes sense to extract this as a constant string and use that string everywhere.

2020-12-24 12:20 UTC, ShubhankarKG commented on new_client/src/components/Header.js
> +						(isDesktop ? "nav-item-desk" : "nav-item-mob") + " curr-page"
By appending `curr-page`, we imply that this is the current page, if I am not wrong. So the logic should be, whenever we click on the route, `curr-page` should be appended to the already existing classNames. The code currently highlights the Home route, which is correct, but not accurate.

2020-12-24 12:20 UTC, ShubhankarKG commented on new_client/src/components/Header.css
> +	font-weight: bold;
Could we also have a green underline here, please :pray:

2021-01-14 10:02 UTC, Saif807380 commented
We wanted to change the design a bit - 

- A full-length navbar would look good on the final website.
- Login and Sign up should be on the right whereas everything else on the left.
- Use the CoC logo as Nav brand on the left

2021-02-10 10:07 UTC, ShubhankarKG commented
Since I've merged #102 that has all the commits from this one, we can close this one out.

Thanks for the help with the navbar!

2021-02-10 10:07 UTC, closed without merging